Convert module to TypeScript
helmetjs/hide-powered-by pull request #3
Opened 2019-05-25 12:06 UTC by gzog

**Description**
- Addresses: #2 
- Use same configuration found in latest version of [expect-ct](https://github.com/helmetjs/expect-ct/tree/21aa018565f96f4a8361c34e374ed4b817d0efcc)

2019-05-25 17:33 UTC, EvanHahn requested changes
This is great—thanks so much for doing this!!

A few minor tweaks to make:

1. Could you remove the Standard.js badge from the readme, now that we're not using it?
2. Could you fill in the changelog or just remove it? And could you remove the reference to the changelog from the readme?

Again, this is super helpful—thanks for doing this!

2019-05-25 17:33 UTC, EvanHahn commented on test/index.test.ts
> +
Nit: could you remove this line?

2019-05-25 17:33 UTC, EvanHahn commented on package.json
> +  "files": [
Now that you've added this, could you `git rm .npmignore`?

2019-05-26 16:11 UTC, gzog commented
@EvanHahn Hey Evan. Thanks for feedback!
Made the following updates based on your comments:
- [x] Removed CHANGELOG.md
- [x] Removed reference to changelog in README.md
- [x] Removed reference to Standard.js badge in README.md
- [x] Removed redundant line in index.test.ts
- [x] Removed .npmignore

2019-05-26 18:49 UTC, EvanHahn approved these changes
Thanks so much for doing this! I'll merge and deploy shortly.

2019-05-26 18:54 UTC, merged

2019-05-26 19:07 UTC, EvanHahn commented
This has been released in `hide-powered-by@1.1.0`! This was a big help, thanks!!

Please add yourself to the [contributors list](https://github.com/helmetjs/helmetjs.github.io/blob/master/contributors/index.md) when you have a moment.